<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>prn</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~z</string>
	<key>name</key>
	<string>ZPL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#command</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>command</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#format</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#control</string>
				</dict>
			</array>
			<key>repository</key>
			<dict>
				<key>control</key>
				<dict>
					<key>match</key>
					<string>(?i)(~.{2})</string>
					<key>name</key>
					<string>constant.language.zpl</string>
				</dict>
				<key>format</key>
				<dict>
					<key>match</key>
					<string>(?i)(\^.{2})</string>
					<key>name</key>
					<string>constant.language.zpl</string>
				</dict>
			</dict>
		</dict>
		<key>string</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=\^FD).+(?=\^FS)</string>
			<key>name</key>
			<string>string</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.zpl</string>
	<key>tabTrigger</key>
	<string></string>
	<key>uuid</key>
	<string>E98E5774-8CD6-4F18-9C6F-A01D572D33DA</string>
</dict>
</plist>
